language: swift
osx_image: xcode10.1
branches:
  only:
    - master
script:
    - xcodebuild clean test -project DangerTest.xcodeproj -scheme DangerTest -destination "platform=iOS Simulator,name=iPhone 8,OS=12.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
